# Generated by Django 3.2.9 on 2021-11-17 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='hashtags',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='latitude',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='place',
            name='longitude',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='place',
            name='search',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
