# Generated by Django 3.2.9 on 2021-11-18 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_serie'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='photo',
            field=models.ImageField(blank=True, default='', null=True, upload_to='user_images/'),
        ),
    ]
