# Generated by Django 3.2.9 on 2021-11-18 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20211118_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='photo',
            field=models.ImageField(blank=True, default='user_images/default.jpg', null=True, upload_to='user_images/'),
        ),
        migrations.AlterField(
            model_name='serie',
            name='photo',
            field=models.ImageField(blank=True, default='user_images/default.jpg', null=True, upload_to='user_images/'),
        ),
    ]
