# Generated by Django 3.2.9 on 2021-11-18 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_serie_is_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='address',
            field=models.CharField(default='-', max_length=255),
            preserve_default=False,
        ),
    ]
