# Generated by Django 3.2.9 on 2021-11-18 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_place_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='views',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='serie',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
